# Generated by Django 5.0.4 on 2024-08-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerApp', '0002_alter_ownerdatabase_mail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdatabase',
            name='mail_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ownerdatabase',
            name='owner_id',
            field=models.IntegerField(),
        ),
    ]
