# Generated by Django 5.0.4 on 2024-08-06 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerApp', '0003_alter_ownerdatabase_mail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdatabase',
            name='mail_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ownerdatabase',
            name='owner_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HosteldataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelid', models.IntegerField()),
                ('hostelname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=12)),
                ('singleshare', models.CharField(max_length=10)),
                ('singleshare_roomno_start', models.IntegerField(null=True)),
                ('singleshare_roomno_end', models.IntegerField(null=True)),
                ('singleshare_fee', models.IntegerField(null=True)),
                ('twoshare', models.CharField(max_length=10)),
                ('twoshare_roomno_start', models.IntegerField(null=True)),
                ('twoshare_roomno_end', models.IntegerField(null=True)),
                ('twoshare_fee', models.IntegerField(null=True)),
                ('threeshare', models.CharField(max_length=10)),
                ('threeshare_roomno_start', models.IntegerField(null=True)),
                ('threeshare_roomno_end', models.IntegerField(null=True)),
                ('threeshare_fee', models.IntegerField(null=True)),
                ('fourshare', models.CharField(max_length=10)),
                ('fourshare_roomno_start', models.IntegerField(null=True)),
                ('fourshare_roomno_end', models.IntegerField(null=True)),
                ('fourshare_fee', models.IntegerField(null=True)),
                ('fiveshare', models.CharField(max_length=10)),
                ('fiveshare_roomno_start', models.IntegerField(null=True)),
                ('fiveshare_roomno_end', models.IntegerField(null=True)),
                ('fiveshare_fee', models.IntegerField(null=True)),
                ('wifi', models.CharField(max_length=10)),
                ('washmachine', models.CharField(max_length=10)),
                ('minwater', models.CharField(max_length=10)),
                ('lift', models.CharField(max_length=10)),
                ('hotwater', models.CharField(max_length=10)),
                ('cctv', models.CharField(max_length=10)),
                ('lockers', models.CharField(max_length=10)),
                ('tv', models.CharField(max_length=10)),
                ('monday_bf', models.CharField(max_length=50)),
                ('monday_launch', models.CharField(max_length=50)),
                ('monday_dinner', models.CharField(max_length=50)),
                ('tuesday_bf', models.CharField(max_length=50)),
                ('tuesday_launch', models.CharField(max_length=50)),
                ('tuesday_dinner', models.CharField(max_length=50)),
                ('wednesday_bf', models.CharField(max_length=50)),
                ('wednesday_launch', models.CharField(max_length=50)),
                ('wednesday_dinner', models.CharField(max_length=50)),
                ('thursday_bf', models.CharField(max_length=50)),
                ('thursday_launch', models.CharField(max_length=50)),
                ('thursday_dinner', models.CharField(max_length=50)),
                ('friday_bf', models.CharField(max_length=50)),
                ('friday_launch', models.CharField(max_length=50)),
                ('friday_dinner', models.CharField(max_length=50)),
                ('saturday_bf', models.CharField(max_length=50)),
                ('saturday_launch', models.CharField(max_length=50)),
                ('saturday_dinner', models.CharField(max_length=50)),
                ('sunday_bf', models.CharField(max_length=50)),
                ('sunday_launch', models.CharField(max_length=50)),
                ('sunday_dinner', models.CharField(max_length=50)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OwnerApp.ownerdatabase')),
            ],
            options={
                'db_table': 'ownerapp_hosteldatabase',
            },
        ),
    ]
