# Generated by Django 5.0.4 on 2024-08-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerApp', '0004_alter_ownerdatabase_mail_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosteldatabase',
            name='userid',
        ),
    ]
