# Generated by Django 5.0.4 on 2024-08-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerApp', '0005_remove_hosteldatabase_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldatabase',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OwnerApp.ownerdatabase'),
        ),
    ]
