# Generated by Django 5.0.4 on 2024-08-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerApp', '0006_hosteldatabase_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelid', models.IntegerField()),
                ('sharing', models.CharField(max_length=30)),
                ('roomno', models.IntegerField()),
                ('bedid', models.CharField(max_length=30)),
            ],
        ),
    ]
