# Generated by Django 5.0.4 on 2024-08-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerApp', '0007_roomdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdatabase',
            name='bedno',
            field=models.IntegerField(null=True),
        ),
    ]
