# Generated by Django 5.0.4 on 2024-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerApp', '0008_roomdatabase_bedno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdatabase',
            name='bedno',
            field=models.IntegerField(),
        ),
    ]
